from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass
from itertools import combinations, product
from typing import Iterable

from projected_sparse_training_common import build_projected_support
from utils import _commutator_pauli_labels_unchecked, all_pauli_labels, pauli_weight, sort_pauli_labels


@dataclass(frozen=True)
class KrylovSupportConfig:
    target_terms: int
    max_depth: int = 8
    max_frontier: int = 65536
    min_score: float = 0.0


def _operator_scores(operator) -> dict[str, float]:
    return {str(label): float(abs(coeff)) for label, coeff in operator.terms.items() if abs(coeff) > 0.0}


def _ranked(scores: dict[str, float]) -> list[tuple[str, float]]:
    return sorted(scores.items(), key=lambda item: (item[1], -pauli_weight(item[0]), item[0]), reverse=True)


def _commutator_scores(left_scores: dict[str, float], right_scores: dict[str, float]) -> dict[str, float]:
    generated: defaultdict[str, float] = defaultdict(float)
    for left_label, left_score in left_scores.items():
        if left_score <= 0.0:
            continue
        for right_label, right_score in right_scores.items():
            if right_score <= 0.0:
                continue
            item = _commutator_pauli_labels_unchecked(left_label, right_label)
            if item is None:
                continue
            phase, out_label = item
            generated[out_label] += float(abs(phase)) * float(left_score) * float(right_score)
    return dict(generated)


def _limited(scores: dict[str, float], max_terms: int) -> dict[str, float]:
    return dict(_ranked(scores)[: max(int(max_terms), 1)])


def _label_from_sites(n_qubits: int, sites: tuple[int, ...], symbols: tuple[str, ...]) -> str:
    chars = ["I"] * n_qubits
    for site, symbol in zip(sites, symbols, strict=True):
        chars[site] = symbol
    return "".join(chars)


def _locality_completion_labels(
    *,
    n_qubits: int,
    excluded: set[str],
    needed: int,
) -> list[str]:
    """Fill a support budget with deterministic low-locality Pauli strings.

    Krylov-generated terms remain the priority. This completion is only used
    when the generated pool is smaller than the requested fixed output budget.
    It prefers lower Pauli weight and shorter geometric span before lexical
    order, which is a conservative locality/geometry prior rather than random
    support padding.
    """

    if needed <= 0:
        return []
    completion: list[str] = []
    for weight in range(1, n_qubits + 1):
        candidates: list[tuple[int, tuple[int, ...], tuple[str, ...], str]] = []
        for sites in combinations(range(n_qubits), weight):
            span = sites[-1] - sites[0] + 1
            for symbols in product(("X", "Y", "Z"), repeat=weight):
                label = _label_from_sites(n_qubits, sites, symbols)
                if label in excluded:
                    continue
                candidates.append((span, sites, symbols, label))
        for _, _, _, label in sorted(candidates, key=lambda item: (item[0], item[1], item[2])):
            completion.append(label)
            excluded.add(label)
            if len(completion) >= needed:
                return completion
    return completion


def nested_commutator_agp_scores(h0, h1, config: KrylovSupportConfig) -> tuple[dict[str, float], dict[str, object]]:
    """Generate a bounded Krylov-style AGP candidate pool.

    The seed is the order-1 variational AGP direction, ``i[H, dH]`` up to a
    real scalar. Deeper candidates are generated by repeated commutators with
    the Hamiltonian endpoint terms. This stays in Pauli-coordinate space and
    never enumerates the full ``4**q`` basis.
    """

    if config.target_terms <= 0:
        raise ValueError("target_terms must be positive.")
    h_scores = {
        label: max(abs(h0.coefficient(label)), abs(h1.coefficient(label)))
        for label in sorted(set(h0.labels) | set(h1.labels))
    }
    delta_scores = _operator_scores(h1 - h0)
    endpoint_scores = _commutator_scores(h_scores, delta_scores)
    if not endpoint_scores:
        raise RuntimeError("Cannot build Krylov AGP support from a zero endpoint commutator.")

    all_scores: defaultdict[str, float] = defaultdict(float)
    frontier = _limited(endpoint_scores, config.max_frontier)
    depth_counts: dict[str, int] = {}
    for label, score in frontier.items():
        all_scores[label] += score
    depth_counts["1"] = len(frontier)

    h_limited = _limited(h_scores, config.max_frontier)
    for depth in range(2, int(config.max_depth) + 1):
        next_scores = _commutator_scores(frontier, h_limited)
        next_scores = {
            label: score / float(depth)
            for label, score in next_scores.items()
            if score > float(config.min_score)
        }
        if not next_scores:
            break
        frontier = _limited(next_scores, config.max_frontier)
        for label, score in frontier.items():
            all_scores[label] += score
        depth_counts[str(depth)] = len(frontier)
        if len(all_scores) >= int(config.target_terms) and depth >= 3:
            # Continue at least through depth 3 so the pool is not merely the
            # l=1 endpoint commutator dressed once by H.
            break

    metadata = {
        "agp_support_strategy": "nested_commutator_krylov_pool",
        "selection_rule": (
            "AGP labels are selected from a bounded nested-commutator pool seeded "
            "by the order-1 direction i[H, dH] and expanded through commutators "
            "with endpoint Hamiltonian terms."
        ),
        "selection_caveat": "Generated sparse pool; it is not an exhaustive 4**q AGP basis.",
        "requested_agp_terms": int(config.target_terms),
        "generated_agp_candidate_terms": len(all_scores),
        "max_depth": int(config.max_depth),
        "max_frontier": int(config.max_frontier),
        "depth_candidate_counts": depth_counts,
        "endpoint_seed_terms": len(endpoint_scores),
    }
    return dict(all_scores), metadata


def select_krylov_agp_labels(h0, h1, config: KrylovSupportConfig) -> tuple[list[str], dict[str, object]]:
    scores, metadata = nested_commutator_agp_scores(h0, h1, config)
    selected = [
        label
        for label, _ in _ranked(scores)[: min(int(config.target_terms), len(scores))]
        if pauli_weight(label) > 0
    ]
    completion = _locality_completion_labels(
        n_qubits=int(h0.n_qubits),
        excluded=set(selected),
        needed=int(config.target_terms) - len(selected),
    )
    selected.extend(completion)
    metadata = dict(metadata)
    metadata["selected_agp_terms"] = len(selected)
    metadata["krylov_selected_agp_terms"] = len(selected) - len(completion)
    metadata["locality_completion_terms"] = len(completion)
    metadata["locality_completion_rule"] = (
        "If the bounded Krylov pool is smaller than K, fill the fixed output "
        "budget with non-random Pauli strings ordered by increasing weight, "
        "shorter geometric span, site tuple, and local Pauli symbols."
    )
    metadata["selected_weight_counts"] = {
        str(weight): sum(pauli_weight(label) == weight for label in selected)
        for weight in sorted({pauli_weight(label) for label in selected})
    }
    metadata["top_generated_agp_candidates"] = [
        {"label": label, "score": float(score), "order": pauli_weight(label)}
        for label, score in _ranked(scores)[: min(64, len(scores))]
    ]
    return sort_pauli_labels(selected), metadata


def build_krylov_projected_support(
    h0,
    h1,
    *,
    agp_top_k: int,
    intermediate_top_k: int,
    residual_top_k: int,
    explicit_agp_labels: Iterable[str] | None = None,
    residual_labels: list[str] | None = None,
    stage: int = 0,
    max_depth: int = 8,
    max_frontier: int = 65536,
) -> dict[str, object]:
    if explicit_agp_labels is None:
        agp_labels, krylov_metadata = select_krylov_agp_labels(
            h0,
            h1,
            KrylovSupportConfig(
                target_terms=int(agp_top_k),
                max_depth=int(max_depth),
                max_frontier=int(max_frontier),
            ),
        )
    else:
        agp_labels = sort_pauli_labels(str(label) for label in explicit_agp_labels)
        krylov_metadata = {
            "agp_support_strategy": "explicit_krylov_labels",
            "selected_agp_terms": len(agp_labels),
        }

    support = build_projected_support(
        h0,
        h1,
        agp_top_k=len(agp_labels),
        intermediate_top_k=int(intermediate_top_k),
        residual_top_k=int(residual_top_k),
        agp_labels=agp_labels,
        residual_labels=residual_labels,
        stage=stage,
    )
    metadata = dict(support["metadata"])
    metadata.update(krylov_metadata)
    metadata["agp_top_k"] = int(agp_top_k)
    metadata["agp_terms"] = len(agp_labels)
    metadata["residual_terms"] = len(support["residual_labels"])
    support = dict(support)
    support["metadata"] = metadata
    return support


def build_full_pauli_projected_support(
    h0,
    h1,
    *,
    agp_top_k: int,
    intermediate_top_k: int,
    residual_top_k: int,
    explicit_agp_labels: Iterable[str] | None = None,
    residual_labels: list[str] | None = None,
    stage: int = 0,
) -> dict[str, object]:
    full_labels = all_pauli_labels(int(h0.n_qubits))
    expected = 4 ** int(h0.n_qubits)
    if int(agp_top_k) != expected:
        raise ValueError(
            "full_pauli_basis support requires agp_top_k == 4**n_qubits; "
            f"got agp_top_k={agp_top_k}, expected={expected}."
        )
    if explicit_agp_labels is not None:
        supplied = sort_pauli_labels(str(label) for label in explicit_agp_labels)
        if supplied != full_labels:
            raise ValueError("Explicit AGP labels do not match the full Pauli basis.")
    if residual_labels is not None:
        supplied_residual = sort_pauli_labels(residual_labels)
        if supplied_residual != full_labels:
            raise ValueError("Explicit residual labels do not match the full Pauli basis.")
    metadata = {
        "strategy": "full_pauli_projected_basis",
        "agp_support_strategy": "full_pauli_basis",
        "selection_rule": (
            "For q<=8 exact-output diagnostics, AGP, intermediate, and residual "
            "labels are the complete 4**q Pauli basis including the identity."
        ),
        "selection_caveat": (
            "The identity direction is included to match the full 4**q output "
            "budget, although it is gauge-trivial in commutator-based AGP losses."
        ),
        "stage": int(stage),
        "full_pauli_basis_size": expected,
        "includes_identity": True,
        "agp_terms": len(full_labels),
        "intermediate_terms": len(full_labels),
        "residual_terms": len(full_labels),
        "agp_top_k": int(agp_top_k),
        "intermediate_top_k": int(intermediate_top_k),
        "residual_top_k": int(residual_top_k),
        "hamiltonian_terms": len(sort_pauli_labels(set(h0.labels) | set(h1.labels))),
        "agp_weight_counts": {
            str(weight): sum(pauli_weight(label) == weight for label in full_labels)
            for weight in sorted({pauli_weight(label) for label in full_labels})
        },
    }
    return {
        "agp_labels": full_labels,
        "intermediate_labels": full_labels,
        "residual_labels": full_labels,
        "metadata": metadata,
    }


def build_configured_projected_support(
    h0,
    h1,
    *,
    agp_top_k: int,
    intermediate_top_k: int,
    residual_top_k: int,
    support_selection: dict[str, object] | None = None,
    explicit_agp_labels: Iterable[str] | None = None,
    residual_labels: list[str] | None = None,
    stage: int = 0,
) -> dict[str, object]:
    selection = support_selection if isinstance(support_selection, dict) else {}
    strategy = str(selection.get("strategy", "endpoint_commutator"))
    if strategy == "full_pauli_basis":
        return build_full_pauli_projected_support(
            h0,
            h1,
            agp_top_k=agp_top_k,
            intermediate_top_k=intermediate_top_k,
            residual_top_k=residual_top_k,
            explicit_agp_labels=explicit_agp_labels,
            residual_labels=residual_labels,
            stage=stage,
        )
    if strategy == "nested_commutator_krylov_pool":
        return build_krylov_projected_support(
            h0,
            h1,
            agp_top_k=agp_top_k,
            intermediate_top_k=intermediate_top_k,
            residual_top_k=residual_top_k,
            explicit_agp_labels=explicit_agp_labels,
            residual_labels=residual_labels,
            stage=stage,
            max_depth=int(selection.get("max_depth", 8)),
            max_frontier=int(selection.get("max_frontier", 65536)),
        )
    if strategy in {"endpoint_commutator", "largest_generated_commutator_terms"}:
        support = build_projected_support(
            h0,
            h1,
            agp_top_k=int(agp_top_k),
            intermediate_top_k=int(intermediate_top_k),
            residual_top_k=int(residual_top_k),
            agp_labels=None if explicit_agp_labels is None else sort_pauli_labels(str(label) for label in explicit_agp_labels),
            residual_labels=residual_labels,
            stage=stage,
        )
        metadata = dict(support["metadata"])
        metadata["agp_support_strategy"] = strategy
        metadata["selection_caveat"] = "Generated sparse support; it is not an exhaustive 4**q AGP basis."
        support = dict(support)
        support["metadata"] = metadata
        return support
    raise ValueError(f"Unsupported AGP support-selection strategy: {strategy!r}.")
